


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pg_trgm" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."get_dashboard_metrics"() RETURNS json
    LANGUAGE "plpgsql"
    AS $$
declare result json;
begin
  select json_build_object(

    'summary', (
      select json_build_object(
        'numberSalesToday', count(*),
        'totalSalesToday', sum(subtotal)
      )
      from "salesItems"
      where date(created_at) = current_date
    ),
    'inventory', (
      select json_build_object(
        'totaStock', count(*),
        'lowStock', count(*) filter(where stock <= 5)
      )
      from "products"
    )
    
  
  ) into result;
  return result;
  end;
  $$;


ALTER FUNCTION "public"."get_dashboard_metrics"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_product_inventory"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$                           
     BEGIN                                           
         INSERT INTO public.inventory (product_id,   
     business_id, stock, min_stock)                  
         VALUES (new.id, new.business_id, 0, 0);     
         RETURN NEW;                                 
     END;                                            
     $$;


ALTER FUNCTION "public"."handle_new_product_inventory"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."businesses" (
    "business_name" "text" NOT NULL,
    "owner_name" "text" NOT NULL,
    "email" "text" NOT NULL,
    "phone" "text" NOT NULL,
    "created_at" "date" DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "business_logo" "text",
    "ticket_footer" "text",
    "low_stock_notifications" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."businesses" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" bigint NOT NULL,
    "created_at" "date" DEFAULT "now"() NOT NULL,
    "business_id" "uuid" NOT NULL,
    "name" character varying NOT NULL
);


ALTER TABLE "public"."categories" OWNER TO "postgres";


ALTER TABLE "public"."categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."inventory" (
    "id" bigint NOT NULL,
    "business_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "product_id" bigint NOT NULL,
    "stock" bigint DEFAULT '0'::bigint NOT NULL,
    "min_stock" bigint DEFAULT '0'::bigint,
    "created_at" "date" DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."inventory" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."inventory_movements" (
    "id" bigint NOT NULL,
    "product_id" bigint NOT NULL,
    "type" "text" NOT NULL,
    "quantity" bigint NOT NULL,
    "created_at" "date" DEFAULT "now"() NOT NULL,
    "unit_cost" numeric DEFAULT '0'::numeric NOT NULL,
    "business_id" "uuid" NOT NULL,
    "notes" "text"
);


ALTER TABLE "public"."inventory_movements" OWNER TO "postgres";


ALTER TABLE "public"."inventory_movements" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."inventoryMovements_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."inventory" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."inventory_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."products" (
    "id" bigint NOT NULL,
    "business_id" "uuid" NOT NULL,
    "category_id" bigint,
    "name" "text" NOT NULL,
    "sku" "text",
    "price" numeric NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" "date" DEFAULT "now"() NOT NULL,
    "track_stock" boolean DEFAULT true,
    "unit_cost" numeric DEFAULT '0'::numeric NOT NULL
);


ALTER TABLE "public"."products" OWNER TO "postgres";


ALTER TABLE "public"."products" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "user_id" "uuid" NOT NULL,
    "role" "text" DEFAULT 'cajero'::"text" NOT NULL,
    "created_at" "date" DEFAULT "now"(),
    "display_name" "text",
    "profile_id" bigint NOT NULL,
    CONSTRAINT "profiles_role_check" CHECK (("role" = ANY (ARRAY['admin'::"text", 'cajero'::"text"])))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


ALTER TABLE "public"."profiles" ALTER COLUMN "profile_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."profiles_profile_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."returns" (
    "id" bigint NOT NULL,
    "sale_id" bigint NOT NULL,
    "business_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "reason" "text" NOT NULL,
    "created_at" "date" NOT NULL,
    "total_amount" double precision NOT NULL
);


ALTER TABLE "public"."returns" OWNER TO "postgres";


ALTER TABLE "public"."returns" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."returns_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."returns_items" (
    "id" bigint NOT NULL,
    "return_id" bigint NOT NULL,
    "product_id" bigint NOT NULL,
    "quantity" bigint NOT NULL,
    "unit_price" bigint NOT NULL,
    "subtotal" bigint NOT NULL,
    "created_at" "date" NOT NULL
);


ALTER TABLE "public"."returns_items" OWNER TO "postgres";


ALTER TABLE "public"."returns_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."returns_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."salesItems" (
    "id" bigint NOT NULL,
    "sale_id" bigint NOT NULL,
    "product_id" bigint NOT NULL,
    "quantity" bigint NOT NULL,
    "unit_price" numeric NOT NULL,
    "subtotal" numeric NOT NULL,
    "created_at" "date" NOT NULL,
    "track_stock" boolean,
    "unit_cost" numeric DEFAULT '0'::numeric NOT NULL
);


ALTER TABLE "public"."salesItems" OWNER TO "postgres";


ALTER TABLE "public"."salesItems" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."salesItems_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."salesTickets" (
    "id" bigint NOT NULL,
    "total_amount" numeric NOT NULL,
    "payment_method" character varying NOT NULL,
    "status" character varying DEFAULT 'completed'::character varying,
    "created_at" "date" NOT NULL,
    "business_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."salesTickets" OWNER TO "postgres";


ALTER TABLE "public"."salesTickets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."salesTickets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."vw_avg_ticket" WITH ("security_invoker"='on') AS
 SELECT "business_id",
    "created_at" AS "sale_date",
    ("count"("id"))::integer AS "sale_count",
    ("sum"("total_amount"))::bigint AS "total_amount",
    (("sum"("total_amount") / (NULLIF("count"("id"), 0))::numeric))::bigint AS "avg_ticket"
   FROM "public"."salesTickets" "st"
  WHERE (("status")::"text" <> 'returned'::"text")
  GROUP BY "business_id", "created_at";


ALTER VIEW "public"."vw_avg_ticket" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_bottom_products" WITH ("security_invoker"='on') AS
 SELECT "p"."business_id",
    "p"."id" AS "product_id",
    "p"."name" AS "product_name",
    (COALESCE("sum"("si"."quantity"), (0)::numeric))::integer AS "total_quantity_sold",
    (COALESCE("sum"("si"."subtotal"), (0)::numeric))::bigint AS "total_revenue"
   FROM (("public"."products" "p"
     LEFT JOIN "public"."salesItems" "si" ON (("si"."product_id" = "p"."id")))
     LEFT JOIN "public"."salesTickets" "st" ON ((("st"."id" = "si"."sale_id") AND (("st"."status")::"text" <> 'returned'::"text"))))
  WHERE ("p"."is_active" = true)
  GROUP BY "p"."business_id", "p"."id", "p"."name";


ALTER VIEW "public"."vw_bottom_products" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_daily_sales" WITH ("security_invoker"='on') AS
 SELECT "business_id",
    "created_at" AS "sale_date",
    ("count"("id"))::integer AS "sale_count",
    ("sum"("total_amount"))::bigint AS "total_amount"
   FROM "public"."salesTickets" "st"
  WHERE (("status")::"text" <> 'returned'::"text")
  GROUP BY "business_id", "created_at";


ALTER VIEW "public"."vw_daily_sales" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_inventory_valuation" WITH ("security_invoker"='on') AS
 SELECT "p"."business_id",
    "p"."id" AS "product_id",
    "p"."name" AS "product_name",
    (COALESCE("i"."stock", (0)::bigint))::integer AS "current_stock",
    ("p"."unit_cost")::bigint AS "unit_cost",
    (((COALESCE("i"."stock", (0)::bigint))::numeric * "p"."unit_cost"))::bigint AS "total_value"
   FROM ("public"."products" "p"
     LEFT JOIN "public"."inventory" "i" ON (("i"."product_id" = "p"."id")))
  WHERE (("p"."is_active" = true) AND ("p"."track_stock" = true));


ALTER VIEW "public"."vw_inventory_valuation" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_product_performance" WITH ("security_invoker"='on') AS
 SELECT "p"."business_id",
    "p"."id" AS "product_id",
    "p"."name" AS "product_name",
    "p"."sku",
    (COALESCE("sum"("si"."quantity"), (0)::numeric))::integer AS "total_quantity_sold",
    (COALESCE("sum"("si"."subtotal"), (0)::numeric))::bigint AS "total_revenue",
    (COALESCE("i"."stock", (0)::bigint))::integer AS "current_stock",
    (COALESCE("i"."min_stock", (0)::bigint))::integer AS "min_stock",
    ("p"."price")::bigint AS "unit_price",
    "p"."track_stock"
   FROM ((("public"."products" "p"
     LEFT JOIN "public"."salesItems" "si" ON (("si"."product_id" = "p"."id")))
     LEFT JOIN "public"."salesTickets" "st" ON ((("st"."id" = "si"."sale_id") AND (("st"."status")::"text" <> 'returned'::"text"))))
     LEFT JOIN "public"."inventory" "i" ON (("i"."product_id" = "p"."id")))
  WHERE ("p"."is_active" = true)
  GROUP BY "p"."business_id", "p"."id", "p"."name", "p"."sku", "i"."stock", "i"."min_stock", "p"."price", "p"."track_stock";


ALTER VIEW "public"."vw_product_performance" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_returns_list" WITH ("security_invoker"='on') AS
 SELECT "r"."id" AS "return_id",
    "r"."business_id",
    "r"."reason",
    "r"."total_amount",
    "r"."created_at" AS "return_date",
    COALESCE("ri"."total_items", 0) AS "total_items_returned"
   FROM ("public"."returns" "r"
     LEFT JOIN ( SELECT "returns_items"."return_id",
            ("sum"("returns_items"."quantity"))::integer AS "total_items"
           FROM "public"."returns_items"
          GROUP BY "returns_items"."return_id") "ri" ON (("ri"."return_id" = "r"."id")));


ALTER VIEW "public"."vw_returns_list" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_returns_summary" WITH ("security_invoker"='on') AS
 SELECT "r"."business_id",
    "r"."created_at" AS "return_date",
    ("count"("r"."id"))::integer AS "return_count",
    ("sum"("r"."total_amount"))::bigint AS "total_amount",
    ("sum"("ri"."quantity"))::integer AS "total_items_returned"
   FROM ("public"."returns" "r"
     JOIN "public"."returns_items" "ri" ON (("ri"."return_id" = "r"."id")))
  GROUP BY "r"."business_id", "r"."created_at";


ALTER VIEW "public"."vw_returns_summary" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_sales_by_category" WITH ("security_invoker"='on') AS
 SELECT "p"."business_id",
    "c"."id" AS "category_id",
    "c"."name" AS "category_name",
    "st"."created_at" AS "sale_date",
    ("count"(DISTINCT "st"."id"))::integer AS "sale_count",
    ("sum"("si"."subtotal"))::bigint AS "total_amount",
    ("sum"("si"."quantity"))::integer AS "total_quantity"
   FROM ((("public"."salesItems" "si"
     JOIN "public"."salesTickets" "st" ON ((("st"."id" = "si"."sale_id") AND (("st"."status")::"text" <> 'returned'::"text"))))
     JOIN "public"."products" "p" ON (("p"."id" = "si"."product_id")))
     JOIN "public"."categories" "c" ON (("c"."id" = "p"."category_id")))
  GROUP BY "p"."business_id", "c"."id", "c"."name", "st"."created_at";


ALTER VIEW "public"."vw_sales_by_category" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_sales_by_payment" WITH ("security_invoker"='on') AS
 SELECT "business_id",
    "payment_method",
    "created_at" AS "sale_date",
    ("count"("id"))::integer AS "sale_count",
    ("sum"("total_amount"))::bigint AS "total_amount"
   FROM "public"."salesTickets" "st"
  WHERE (("status")::"text" <> 'returned'::"text")
  GROUP BY "business_id", "payment_method", "created_at";


ALTER VIEW "public"."vw_sales_by_payment" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_sales_history" AS
SELECT
    NULL::bigint AS "id",
    NULL::numeric AS "total_amount",
    NULL::"date" AS "created_at",
    NULL::character varying AS "payment_method",
    NULL::character varying AS "status",
    NULL::"uuid" AS "business_id",
    NULL::"jsonb" AS "items",
    NULL::integer AS "items_count";


ALTER VIEW "public"."vw_sales_history" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_stock_status" WITH ("security_invoker"='on') AS
 SELECT "p"."business_id",
    "p"."id" AS "product_id",
    "p"."name" AS "product_name",
    "p"."unit_cost",
    "c"."id" AS "category_id",
    "c"."name" AS "category_name",
    (COALESCE("i"."stock", (0)::bigint))::integer AS "current_stock",
    (COALESCE("i"."min_stock", (0)::bigint))::integer AS "min_stock",
    "p"."track_stock",
        CASE
            WHEN ("p"."track_stock" = false) THEN 'sin_control'::"text"
            WHEN (COALESCE("i"."stock", (0)::bigint) <= 0) THEN 'sin_stock'::"text"
            WHEN ((COALESCE("i"."stock", (0)::bigint) <= COALESCE("i"."min_stock", (0)::bigint)) AND (COALESCE("i"."min_stock", (0)::bigint) > 0)) THEN 'stock_bajo'::"text"
            ELSE 'con_stock'::"text"
        END AS "stock_status"
   FROM (("public"."products" "p"
     LEFT JOIN "public"."categories" "c" ON (("c"."id" = "p"."category_id")))
     LEFT JOIN "public"."inventory" "i" ON (("i"."product_id" = "p"."id")))
  WHERE ("p"."is_active" = true);


ALTER VIEW "public"."vw_stock_status" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_top_products" WITH ("security_invoker"='on') AS
 SELECT "p"."business_id",
    "p"."id" AS "product_id",
    "p"."name" AS "product_name",
    ("sum"("si"."quantity"))::integer AS "total_quantity_sold",
    ("sum"("si"."subtotal"))::bigint AS "total_revenue"
   FROM (("public"."salesItems" "si"
     JOIN "public"."salesTickets" "st" ON ((("st"."id" = "si"."sale_id") AND (("st"."status")::"text" <> 'returned'::"text"))))
     JOIN "public"."products" "p" ON (("p"."id" = "si"."product_id")))
  GROUP BY "p"."business_id", "p"."id", "p"."name";


ALTER VIEW "public"."vw_top_products" OWNER TO "postgres";


ALTER TABLE ONLY "public"."businesses"
    ADD CONSTRAINT "businesses_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."inventory_movements"
    ADD CONSTRAINT "inventoryMovements_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."inventory"
    ADD CONSTRAINT "inventory_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("profile_id");



ALTER TABLE ONLY "public"."returns_items"
    ADD CONSTRAINT "returns_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."returns"
    ADD CONSTRAINT "returns_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."salesItems"
    ADD CONSTRAINT "salesItems_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."salesTickets"
    ADD CONSTRAINT "salesTickets_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_categories_business" ON "public"."categories" USING "btree" ("business_id");



CREATE INDEX "idx_inv_mov_business" ON "public"."inventory_movements" USING "btree" ("business_id", "type", "created_at" DESC);



CREATE INDEX "idx_inventory_business" ON "public"."inventory" USING "btree" ("business_id");



CREATE INDEX "idx_inventory_product" ON "public"."inventory" USING "btree" ("product_id");



CREATE INDEX "idx_products_business" ON "public"."products" USING "btree" ("business_id");



CREATE INDEX "idx_products_business_name" ON "public"."products" USING "btree" ("business_id", "name");



CREATE INDEX "idx_products_name_trgm" ON "public"."products" USING "gin" ("name" "extensions"."gin_trgm_ops");



CREATE INDEX "idx_products_sku" ON "public"."products" USING "btree" ("sku");



CREATE INDEX "idx_returns_business_date" ON "public"."returns" USING "btree" ("business_id", "created_at");



CREATE INDEX "idx_salesitems_product" ON "public"."salesItems" USING "btree" ("product_id");



CREATE INDEX "idx_salesitems_sale" ON "public"."salesItems" USING "btree" ("sale_id");



CREATE INDEX "idx_salestickets_business_date" ON "public"."salesTickets" USING "btree" ("business_id", "created_at");



CREATE INDEX "idx_salestickets_business_id" ON "public"."salesTickets" USING "btree" ("business_id");



CREATE INDEX "idx_salestickets_status" ON "public"."salesTickets" USING "btree" ("status");



CREATE OR REPLACE VIEW "public"."vw_sales_history" WITH ("security_invoker"='true') AS
 SELECT "st"."id",
    "st"."total_amount",
    "st"."created_at",
    "st"."payment_method",
    "st"."status",
    "st"."business_id",
    "jsonb_agg"("jsonb_build_object"('id', "si"."id", 'product_id', "si"."product_id", 'quantity', "si"."quantity", 'price', "si"."unit_price", 'subtotal', "si"."subtotal", 'name', COALESCE("p"."name", 'Producto eliminado'::"text")) ORDER BY "si"."id") AS "items",
    ("sum"("si"."quantity"))::integer AS "items_count"
   FROM (("public"."salesTickets" "st"
     JOIN "public"."salesItems" "si" ON (("si"."sale_id" = "st"."id")))
     LEFT JOIN "public"."products" "p" ON (("p"."id" = "si"."product_id")))
  GROUP BY "st"."id";



CREATE OR REPLACE TRIGGER "on_product_created" AFTER INSERT ON "public"."products" FOR EACH ROW EXECUTE FUNCTION "public"."handle_new_product_inventory"();



ALTER TABLE ONLY "public"."businesses"
    ADD CONSTRAINT "businesses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."inventory_movements"
    ADD CONSTRAINT "inventoryMovements_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."inventory"
    ADD CONSTRAINT "inventory_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."inventory_movements"
    ADD CONSTRAINT "inventory_movements_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."inventory"
    ADD CONSTRAINT "inventory_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."returns"
    ADD CONSTRAINT "returns_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."returns_items"
    ADD CONSTRAINT "returns_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."returns_items"
    ADD CONSTRAINT "returns_items_return_id_fkey" FOREIGN KEY ("return_id") REFERENCES "public"."returns"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."returns"
    ADD CONSTRAINT "returns_sale_id_fkey" FOREIGN KEY ("sale_id") REFERENCES "public"."salesTickets"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."salesItems"
    ADD CONSTRAINT "salesItems_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."salesItems"
    ADD CONSTRAINT "salesItems_sale_id_fkey" FOREIGN KEY ("sale_id") REFERENCES "public"."salesTickets"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."salesTickets"
    ADD CONSTRAINT "salesTickets_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "User can view item sales" ON "public"."salesItems" FOR SELECT USING (("auth"."uid"() = ( SELECT "salesTickets"."business_id"
   FROM "public"."salesTickets"
  WHERE ("salesTickets"."id" = "salesItems"."sale_id"))));



CREATE POLICY "Users can do ALL" ON "public"."businesses" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can do ALL" ON "public"."categories" USING (("auth"."uid"() = "business_id")) WITH CHECK (("auth"."uid"() = "business_id"));



CREATE POLICY "Users can do ALL" ON "public"."inventory" USING (("auth"."uid"() = "business_id")) WITH CHECK (("auth"."uid"() = "business_id"));



CREATE POLICY "Users can do ALL" ON "public"."inventory_movements" USING (("business_id" = "auth"."uid"())) WITH CHECK (("business_id" = "auth"."uid"()));



CREATE POLICY "Users can do ALL" ON "public"."products" USING (("auth"."uid"() = "business_id")) WITH CHECK (("auth"."uid"() = "business_id"));



CREATE POLICY "Users can do ALL" ON "public"."profiles" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can do ALL" ON "public"."returns" USING (("auth"."uid"() = "business_id")) WITH CHECK (("auth"."uid"() = "business_id"));



CREATE POLICY "Users can do ALL" ON "public"."salesTickets" USING (("auth"."uid"() = "business_id")) WITH CHECK (("auth"."uid"() = "business_id"));



CREATE POLICY "Users can insert data" ON "public"."returns_items" FOR INSERT WITH CHECK (("auth"."uid"() = ( SELECT "returns"."business_id"
   FROM "public"."returns"
  WHERE ("returns"."id" = "returns_items"."return_id"))));



CREATE POLICY "Users can insert data" ON "public"."salesItems" FOR INSERT WITH CHECK (("auth"."uid"() = ( SELECT "salesTickets"."business_id"
   FROM "public"."salesTickets"
  WHERE ("salesTickets"."id" = "salesItems"."sale_id"))));



ALTER TABLE "public"."businesses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."inventory" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."inventory_movements" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."returns" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."returns_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."salesItems" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."salesTickets" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "user can view returns" ON "public"."returns_items" FOR SELECT USING (("auth"."uid"() = ( SELECT "returns"."business_id"
   FROM "public"."returns"
  WHERE ("returns"."id" = "returns_items"."return_id"))));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



















































































































































































































































GRANT ALL ON FUNCTION "public"."get_dashboard_metrics"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_dashboard_metrics"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_dashboard_metrics"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_product_inventory"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_product_inventory"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_product_inventory"() TO "service_role";


















GRANT ALL ON TABLE "public"."businesses" TO "anon";
GRANT ALL ON TABLE "public"."businesses" TO "authenticated";
GRANT ALL ON TABLE "public"."businesses" TO "service_role";



GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT ALL ON TABLE "public"."categories" TO "authenticated";
GRANT ALL ON TABLE "public"."categories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."inventory" TO "anon";
GRANT ALL ON TABLE "public"."inventory" TO "authenticated";
GRANT ALL ON TABLE "public"."inventory" TO "service_role";



GRANT ALL ON TABLE "public"."inventory_movements" TO "anon";
GRANT ALL ON TABLE "public"."inventory_movements" TO "authenticated";
GRANT ALL ON TABLE "public"."inventory_movements" TO "service_role";



GRANT ALL ON SEQUENCE "public"."inventoryMovements_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."inventoryMovements_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."inventoryMovements_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."inventory_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."inventory_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."inventory_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."products" TO "anon";
GRANT ALL ON TABLE "public"."products" TO "authenticated";
GRANT ALL ON TABLE "public"."products" TO "service_role";



GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."profiles_profile_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."profiles_profile_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."profiles_profile_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."returns" TO "anon";
GRANT ALL ON TABLE "public"."returns" TO "authenticated";
GRANT ALL ON TABLE "public"."returns" TO "service_role";



GRANT ALL ON SEQUENCE "public"."returns_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."returns_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."returns_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."returns_items" TO "anon";
GRANT ALL ON TABLE "public"."returns_items" TO "authenticated";
GRANT ALL ON TABLE "public"."returns_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."returns_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."returns_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."returns_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."salesItems" TO "anon";
GRANT ALL ON TABLE "public"."salesItems" TO "authenticated";
GRANT ALL ON TABLE "public"."salesItems" TO "service_role";



GRANT ALL ON SEQUENCE "public"."salesItems_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."salesItems_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."salesItems_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."salesTickets" TO "anon";
GRANT ALL ON TABLE "public"."salesTickets" TO "authenticated";
GRANT ALL ON TABLE "public"."salesTickets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."salesTickets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."salesTickets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."salesTickets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."vw_avg_ticket" TO "anon";
GRANT ALL ON TABLE "public"."vw_avg_ticket" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_avg_ticket" TO "service_role";



GRANT ALL ON TABLE "public"."vw_bottom_products" TO "anon";
GRANT ALL ON TABLE "public"."vw_bottom_products" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_bottom_products" TO "service_role";



GRANT ALL ON TABLE "public"."vw_daily_sales" TO "anon";
GRANT ALL ON TABLE "public"."vw_daily_sales" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_daily_sales" TO "service_role";



GRANT ALL ON TABLE "public"."vw_inventory_valuation" TO "anon";
GRANT ALL ON TABLE "public"."vw_inventory_valuation" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_inventory_valuation" TO "service_role";



GRANT ALL ON TABLE "public"."vw_product_performance" TO "anon";
GRANT ALL ON TABLE "public"."vw_product_performance" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_product_performance" TO "service_role";



GRANT ALL ON TABLE "public"."vw_returns_list" TO "anon";
GRANT ALL ON TABLE "public"."vw_returns_list" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_returns_list" TO "service_role";



GRANT ALL ON TABLE "public"."vw_returns_summary" TO "anon";
GRANT ALL ON TABLE "public"."vw_returns_summary" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_returns_summary" TO "service_role";



GRANT ALL ON TABLE "public"."vw_sales_by_category" TO "anon";
GRANT ALL ON TABLE "public"."vw_sales_by_category" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_sales_by_category" TO "service_role";



GRANT ALL ON TABLE "public"."vw_sales_by_payment" TO "anon";
GRANT ALL ON TABLE "public"."vw_sales_by_payment" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_sales_by_payment" TO "service_role";



GRANT ALL ON TABLE "public"."vw_sales_history" TO "anon";
GRANT ALL ON TABLE "public"."vw_sales_history" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_sales_history" TO "service_role";



GRANT ALL ON TABLE "public"."vw_stock_status" TO "anon";
GRANT ALL ON TABLE "public"."vw_stock_status" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_stock_status" TO "service_role";



GRANT ALL ON TABLE "public"."vw_top_products" TO "anon";
GRANT ALL ON TABLE "public"."vw_top_products" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_top_products" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


  create policy "Give anon users access to JPG images in folder 1peuqw_0"
  on "storage"."objects"
  as permissive
  for update
  to anon
using (((bucket_id = 'logos'::text) AND (storage.extension(name) = 'png'::text) AND (lower((storage.foldername(name))[1]) = 'logos'::text) AND (auth.role() = 'anon'::text)));



  create policy "Give anon users access to JPG images in folder 1peuqw_1"
  on "storage"."objects"
  as permissive
  for select
  to anon
using (((bucket_id = 'logos'::text) AND (storage.extension(name) = 'png'::text) AND (lower((storage.foldername(name))[1]) = 'logos'::text) AND (auth.role() = 'anon'::text)));



  create policy "Give anon users access to JPG images in folder 1peuqw_2"
  on "storage"."objects"
  as permissive
  for insert
  to anon
with check (((bucket_id = 'logos'::text) AND (storage.extension(name) = 'png'::text) AND (lower((storage.foldername(name))[1]) = 'logos'::text) AND (auth.role() = 'anon'::text)));



